version: 4.0

rx_params:
  rx_interface: enp0s31f6
  rx_ping_interval: 0.001 # TODO: eventually be dynamic?
  ping_target_ip: 192.168.0.246
  ping_src_addr: DE:AD:BE:EF:DE:AD
  ping_source_port: 25565 # interchangeable
  ping_dest_port: 80 # Should remain the same

decoder_params:
  preamble: [1,1,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,0,1,0,1,0,1,1,1,0,1,1,0,0,0,]
  packet_length: 64
  system:
    back_offset: 101
    front_offset: 1
    zero_percentage: 70
    sync_threshold: 7

utilities:
  mode: normal
  timeout: 100
  logging:
    console_output: True
    debug_outputs: True